In [1]:
from io import StringIO
import pandas as pd

raw_csv = """product_id,name,price,category,rating,stock
123, Phone X , 7999 , Mobiles ,4.5,Yes
"""

products = pd.read_csv(StringIO(raw_csv), dtype={"price": "string"})

print("Before cleaning")
display(products)

products["name"] = products["name"].str.strip()
products["price"] = products["price"].str.strip().astype(int)
products["category"] = products["category"].str.strip().str.lower()

print("After cleaning")
display(products)
print("Price data type:", products["price"].dtype)

Before cleaning

   product_id       name   price   category  rating stock
0         123   Phone X    7999    Mobiles      4.5   Yes

After cleaning

   product_id     name  price category  rating stock
0         123  Phone X   7999  mobiles     4.5   Yes

Price data type: int64